name: generate_convs_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pymupdf     # for pdf reading
  - pip:
      - openai