name: generate_convs_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - pymupdf
  - jsonschema
  - python-dotenv
  - pip
  - pip:
      - openai